
import { SQPQuestion } from '../../types';

export const SQP_QUESTIONS: SQPQuestion[] = [
  // 2022-23
  {
    id: 'u1-q5-sqp-2023',
    year: '2022-23',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '5',
    question: 'Read the following statements carefully:\nStatement 1: Net investment is a stock concept.\nStatement 2: Capital is a flow concept.\nIn the light of the given statements, choose the correct alternative from the following:',
    optionA: 'Statement 1 is true and statement 2 is false',
    optionB: 'Statement 1 is false and statement 2 is true',
    optionC: 'Both statements 1 and 2 are true',
    optionD: 'Both statements 1 and 2 are false',
    answer: 'D',
    aiExplanation: 'Teacher\'s Voice: **Concept Check!**\n- **Investment (Net or Gross)** happens over a period of time, so it is a **Flow** concept (like ₹10,000 invested per month). It measures the addition to the capital stock over a specific period.\n- **Capital** is the total stock of assets measured at a specific point in time, so it is a **Stock** concept (like ₹5 Lakhs in the bank on March 31st). It serves as the base for future production.\nSince both definitions are flipped in the statements, both statements are false.'
  },
  {
    id: 'u1-q5-or-sqp-2023',
    year: '2022-23',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '5 OR',
    question: 'Read the following figure carefully and choose the correct pair from the alternatives given below:',
    imageUrl: '/assets/images/sqp-2023-q5-or.png',
    optionA: 'Output, Production',
    optionB: 'Value added, Production',
    optionC: 'Output, Disposition',
    optionD: 'Wealth, Development',
    answer: 'C',
    aiExplanation: 'Teacher\'s Voice: **The 3 Phases of Circular Flow!**\nThere are three distinct phases in the circular flow of income:\n1. **Generation Phase (Production):** Producing goods and services. Since it\'s national, it generates National **Output**.\n2. **Distribution Phase (Income):** Factor payments (rent, wages, interest, profit) are distributed, making National Income.\n3. **Disposition Phase (Expenditure):** Households and firms spend their incomes on the produced goods, creating National Expenditure.'
  },
  {
    id: 'u1-q11-sqp-2023',
    year: '2022-23',
    paperType: 'SQP',
    marks: 3,
    type: 'SA',
    questionNumber: '11',
    question: 'Suppose in a hypothetical economy there are only two Firms A and B, Firm A sold goods for ₹ 2,000 to Firm B and purchased goods for ₹ 1,000. Firm B exported goods for ₹ 2,500 and had domestic sales of ₹ 1,500. Calculate Net Domestic Product at market price, if consumption of fixed capital is ₹ 200.',
    markingScheme: 'Value of Output: Firm A = 2,000 (to B). Firm B = 2,500 (exports) + 1,500 (domestic sales) = 4,000. Total = 6,000.\nIntermediate Consumption: Firm A = 1,000 (purchases). Firm B = 2,000 (purchased from A). Total = 3,000.\nValue Addition: Firm A = 1,000. Firm B = 2,000. Total = 3,000.\nGross Domestic Product at Market price = 3,000.\nNet Domestic Product at MP = Gross Domestic Product at Market price – Consumption of Fixed Capital = 3,000 – 200 = ₹ 2,800',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 3 M!**\n\n**1 Mark for calculating Gross Value Added (GVA) for Firm A & B:**\nGross Value Added represents the actual value generated by each firm\'s productive activities.\n- Firm A GVA: 2,000 (Sales) - 1,000 (Purchases) = ₹1,000.\n- Firm B GVA: 4,000 (Exports + Domestic Sales) - 2,000 (Purchased from A) = ₹2,000.\n\n**1 Mark for arriving at Gross Domestic Product at Market Price (GDP at MP):**\nGross Domestic Product at Market Price is the sum total of Gross Value Added by all producing units within the domestic territory.\n- GDP at MP = Total GVA = 1,000 + 2,000 = ₹3,000.\n\n**1 Mark for arriving at Net Domestic Product at Market Price (NDP at MP):**\nTo convert Gross to Net, we subtract the Consumption of Fixed Capital (Depreciation), which accounts for wear and tear of assets.\n- NDP at MP = GDP at MP - Depreciation.\n- NDP at MP = 3,000 - 200 = **₹ 2,800**.'
  },
  {
    id: 'u1-q16-sqp-2023',
    year: '2022-23',
    paperType: 'SQP',
    marks: 6,
    type: 'LA',
    questionNumber: '16',
    question: 'a) Define Gross Domestic Product (GDP) deflator and discuss its importance.\nb) State and discuss any two precautions to be considered while estimating national income by Expenditure Method.',
    markingScheme: 'a) GDP Deflator is the ratio of Nominal to Real GDP. It is a tool which is used to eliminate the effect of price fluctuations in the economy and to determine the real change in physical output of current year. GDP deflator helps in comparison of growth rate of the economy.\nb) Precautions of Expenditure method (any two):\n1. Expenditure on second hand goods is not to be included in the final consumption expenditure as the production of these goods might not be attributed to the current year.\n2. Expenditure on ‘intermediate goods’ are not to be taken into account, to avoid the problem of double counting of value of goods and services.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 6 M!**\n\n**3 Marks for Part (a) - GDP Deflator:**\n- *Definition (1 mark):* It is a simple ratio comparing current prices to base prices. Formula: GDP Deflator = (Nominal GDP / Real GDP) × 100.\n- *Importance (2 marks):* It acts as an inflation checker. Nominal GDP changes when prices change OR when output changes. Real GDP only changes when output changes. By comparing the two, the GDP Deflator strips away the "price effect", allowing economists to measure the *real* physical growth of an economy!\n\n**3 Marks for Part (b) - Expenditure Precautions:**\nState and briefly explain two strict rules:\n1. **Ignore Second-Hand Goods:** Only new goods produced this year count. Buying a 5-year old car doesn\'t add to current production (1.5 marks).\n2. **Ignore Intermediate Goods:** Only expenditure on *final* goods counts. If a baker buys flour to make bread, only the final bread sale is counted to strictly avoid double counting (1.5 marks).'
  },

  // 2023-24
  {
    id: 'u1-q2-sqp-2024',
    year: '2023-24',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '2',
    question: 'For a closed economy (with no foreign trade), which one of the following is correct?',
    optionA: 'GDP = GNP',
    optionB: 'GDP > GNP',
    optionC: 'GDP < GNP',
    optionD: 'GDP + GNP=0',
    answer: 'A',
    aiExplanation: 'Teacher\'s Voice: **A quick logical deduction!**\n- **Rule:** Gross National Product (GNP) = Gross Domestic Product (GDP) + Net Factor Income from Abroad (NFIA).\n- Net Factor Income from Abroad is the difference between factor income earned from the rest of the world and factor income paid to the rest of the world.\n- In a closed economy, there is NO foreign trade or economic interaction with other countries, which means NFIA is absolutely **zero**.\n- Since NFIA is 0, GNP = GDP + 0, meaning they are perfectly equal.'
  },
  {
    id: 'u1-q12a-sqp-2024',
    year: '2023-24',
    paperType: 'SQP',
    marks: 3,
    type: 'SA',
    questionNumber: '12 (A)',
    question: 'On the basis of the given data, estimate the value of Domestic Income:\ni. Household Consumption Expenditure: 600\nii. Gross Fixed Capital Formation: 200\niii. Change in stock: 40\niv. Government Final Consumption Expenditure: 200\nv. Net Exports: (-)40\nvi. Net Indirect Taxes: 120\nvii. Net Factor Income From Abroad: 20\nviii. Consumption of Fixed Capital: 40\n(Amount ₹ in crore)',
    markingScheme: 'Domestic Income (NDP at FC) = (i) + (iv) + (ii) + (iii) + (v) – (viii) – (vi)\n= 600 + 200 + 200 + 40 + (-40) – 40 – 120\n= ₹ 840 crore',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 3 M!**\n\n**1 Mark for calculating Gross Domestic Capital Formation (GDCF):**\nGross Domestic Capital Formation represents total investment in the economy, including both fixed assets and inventory.\n- GDCF = Gross Fixed Capital Formation + Change in Stock = 200 + 40 = 240.\n\n**1 Mark for arriving at Gross Domestic Product at Market Price (GDP at MP):**\nUse the Expenditure Method components: Private Final Consumption Expenditure (PFCE), Government Final Consumption Expenditure (GFCE), GDCF, and Net Exports.\n- GDP at MP = PFCE + GFCE + GDCF + Net Exports.\n- GDP at MP = 600 + 200 + 240 + (-40) = 1,000.\n\n**1 Mark for converting to Domestic Income (Net Domestic Product at Factor Cost, NDP at FC):**\n- To go from Gross to Net, subtract Depreciation (Consumption of Fixed Capital).\n- To go from Market Price to Factor Cost, subtract Net Indirect Taxes (Indirect Taxes minus Subsidies).\n- NDP at FC = GDP at MP - Depreciation - Net Indirect Taxes.\n- NDP at FC = 1,000 - 40 - 120 = **₹ 840 crore**.'
  },
  {
    id: 'u1-q12b-sqp-2024',
    year: '2023-24',
    paperType: 'SQP',
    marks: 3,
    type: 'SA',
    questionNumber: '12 (B)',
    question: 'State the meanings of the following:\n(i) Externalities\n(ii) Operating Surplus\n(iii) Consumption Goods',
    markingScheme: '(i) Externalities refer to benefits (positive externalities)/ harms (negative externalities) which are caused by one entity to another without being paid/ penalised for it.\n(ii) Operating Surplus is the sum total of rent, royalties, interest and profits. It is also known as non-wage income.\n(iii) Goods which are consumed by the ultimate consumers or meet the immediate need of the consumer are called consumption goods. It may include services as well.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 3 M!**\n\n**1 Mark for defining Externalities:**\nThese are side effects (harms or benefits) caused by an entity without being penalized or paid for it.\n\n**1 Mark for defining Operating Surplus:**\nIn the Income Method, this is the "non-wage" income. It is the sum of Rent, Royalty, Interest, and Profit.\n\n**1 Mark for defining Consumption Goods:**\nThese are goods (or services) consumed by the ultimate consumers to satisfy immediate human wants (e.g., clothes, food).'
  },
  {
    id: 'u1-q17-sqp-2024',
    year: '2023-24',
    paperType: 'SQP',
    marks: 6,
    type: 'LA',
    questionNumber: '17',
    question: '(a) Giving valid reasons, explain how the following would be treated while estimating domestic income?\n(i) Payment made by American tourist for goods purchased in India.\n(ii) Tomatoes grown by Ms. Puja in her kitchen garden.\n(b) "Machine purchased by a firm is always a capital good." Do you agree with the given statement? Give valid reasons for your answer.',
    markingScheme: '(a) (i) Yes, included in domestic income as American tourist expenditure is included as exports.\n(ii) No, it will not be included because it is difficult to ascertain their market value, and it is not undertaken for monetary consideration.\n(b) No. A machine purchased by a firm is a capital good when used for production. However, if purchased for resale purposes in the same year, it is an intermediate good.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 3 M!**\n\n**1 Mark for part (a)(i) with reason:**\nYES. It is included in domestic income because American tourist expenditure is treated as exports.\n\n**1 Mark for part (a)(ii) with reason:**\nNO. It will not be included because there is no market value and it was grown for self-consumption, not for monetary consideration.\n\n**1 Mark for part (b) with reason:**\nNO. Meaning of a capital good depends on its **end use**. A machine bought by a firm a capital good if used for production, but it is an intermediate good if purchased for resale.'
  },

  // 2024-25
  {
    id: 'u1-q3-sqp-2025',
    year: '2024-25',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '3',
    question: 'To arrive at the value of Gross Value Added at Market Price (GVAMP) ______ must be added to Gross Value Added (GVA) at Basic Prices.',
    optionA: 'Product Taxes',
    optionB: 'Net Product Taxes',
    optionC: 'Production Taxes',
    optionD: 'Net Production Taxes',
    answer: 'B',
    aiExplanation: 'Teacher\'s Voice: **Visualizing the Tax Hierarchy:**\n1. Gross Value Added (GVA) at Factor Cost + Net *Production* Taxes (taxes on the act of producing, independent of volume) = GVA at Basic Prices.\n2. GVA at Basic Prices + Net *Product* Taxes (taxes related precisely to the volume of output, like GST) = GVA at Market Prices.\nSo, to step up from Basic Prices to Market Prices, we must add Net Product Taxes!'
  },
  {
    id: 'u1-q11b-sqp-2025',
    year: '2024-25',
    paperType: 'SQP',
    marks: 3,
    type: 'SA',
    questionNumber: '11 (B)',
    question: 'On the basis of the given data, estimate the value of Domestic Income (NDPFC):\ni. Household Consumption Expenditure: 800\nii. Gross Business Fixed Capital Formation: 150\niii. Gross Residential Construction Investment: 120\niv. Government Final Consumption Expenditure: 170\nv. Excess of Imports over Exports: 20\nvi. Inventory Investment: 140\nvii. Gross Public Investment: 500\nviii. Net Indirect Taxes: 70\nix. Net Factor Income From Abroad: (-) 50\nx. Consumption of Fixed Capital: 40\n(Amount in ₹ crore)',
    markingScheme: 'Domestic Income (NDPFC) = i + iv + ii + iii + vii + vi – v – x – viii\n= 800 + 170 + 150 + 120 + 500 + 140 – 20 – 40 – 70\n= ₹ 1,750 crore',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 3 M!**\n\n**1 Mark for calculating Gross Domestic Capital Formation (GDCF):**\nGross Domestic Capital Formation is the sum of all fixed investments and inventory investments within the domestic territory.\n- GDCF = Fixed Investments (Business 150 + Residential 120 + Public 500 = 770) + Inventory Investment (140) = 910.\n\n**1 Mark for arriving at Gross Domestic Product at Market Price (GDP at MP):**\nSum the final expenditures: Private Final Consumption Expenditure (PFCE), Government Final Consumption Expenditure (GFCE), GDCF, and Net Exports (Exports minus Imports).\n- GDP at MP = PFCE + GFCE + GDCF + Net Exports (-20).\n- GDP at MP = 800 + 170 + 910 - 20 = 1,860.\n\n**1 Mark for converting to Domestic Income (Net Domestic Product at Factor Cost, NDP at FC):**\n- Gross to Net: Subtract Depreciation (Consumption of Fixed Capital).\n- Market Price (MP) to Factor Cost (FC): Subtract Net Indirect Taxes.\n- NDP at FC = GDP at MP - Depreciation - Net Indirect Taxes.\n- NDP at FC = 1,860 - 40 - 70 = **₹ 1,750 crore**.'
  },
  {
    id: 'u1-q17-sqp-2025',
    year: '2024-25',
    paperType: 'SQP',
    marks: 6,
    type: 'LA',
    questionNumber: '17',
    question: '(I) On the basis of the following hypothetical data:\nYear 2020: Nominal GDP = 3,000, Nominal GDP adjusted to base year prices = 4,000\nYear 2023: Nominal GDP = 4,000, Nominal GDP adjusted to base year prices = 4,500\n(all figures in ₹ crore)\nCalculate the percentage change in Real Gross Domestic Product in the year 2023 using 2020 as the base year.\n(II) “The public investment on the construction of a multi-lane flyover may reduce traffic congestion.”\nOn the basis of the above statement, discuss its likely impact on Gross Domestic Product (GDP) and welfare in an economy.',
    markingScheme: '(I) Percentage change in Real GDP = [Change in Real GDP / Real GDP] x 100\n= [(4,500 – 4,000) / 4,000] x 100\n= 12.5 %\n(II) The public investment on the construction of a multi-lane flyover may impact the GDP positively as good quality infrastructure generally attracts higher investments and may lead to an increase in employment opportunities.\nIt may also lead to a reduction in travel time and lower average transportation costs. Consequently, it may securely increase the well-being and welfare of citizens.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 6 M!**\n\n**3 Marks for Part (I) - Real GDP Calculation:**\n"Nominal GDP adjusted to base year prices" simply means **Real GDP**. \nReal GDP (2020) = 4,000; Real GDP (2023) = 4,500.\nPercentage Change = [(Change in Real GDP) / Base Year Real GDP] × 100.\nCalculation = [(4,500 - 4,000) / 4,000] × 100 = **12.5%**.\n\n**3 Marks for Part (II) - Infrastructure Impact:**\n1. **Impact on GDP:** Building a flyover creates massive construction jobs and orders for cement/steel, directly pushing Gross Domestic Product upward!\n2. **Impact on Welfare:** Faster commutes mean less fuel wasted, less stress, and better productivity. This positive externality directly improves overall human welfare.'
  },
  {
    id: 'u1-q17-or-sqp-2025',
    year: '2024-25',
    paperType: 'SQP',
    marks: 6,
    type: 'LA',
    questionNumber: '17 OR',
    question: '(I) “Basis of classification of final goods into consumption and capital goods depend on the economic nature of its use.”\nDefend or refute the statement, with the help of a suitable example.\n(II) ‘Natural calamities in the hill states of India have led to massive destruction of capital assets.’\nIdentify the type of loss (depreciation or capital loss) indicated in the aforesaid statement. Give valid reasons in support of your answer.',
    markingScheme: '(I) The given statement is defended. Consumption goods are those goods that directly satisfy the wants of the consumer whereas, capital goods are those final goods that are used for further production. It depends entirely upon the economic nature of its use. Example: machinery purchased by a household is a consumption good whereas, if it is purchased by a firm for further production, it acts as a capital good.\n(II) The massive destruction of capital assets caused by recent natural calamities can be considered as capital loss. Capital loss refers to the absolute loss in the value of fixed assets exclusively due to unforeseen circumstances like natural disasters, theft, fires, etc.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 6 M!**\n\n**4 Marks for Part (I) - End Use Concept:**\nDefend the statement definitively!\nA car bought by a family to strictly drive to the mall is fundamentally a "Consumption Good" because it directly satisfies a personal want. However, the exact identical car bought by a taxi company to earn taxi fares is entirely a "Capital Good" actively used for further production. The physical item doesn\'t rigidly matter; the precise **economic end-use** defines the exact class!\n\n**2 Marks for Part (II) - Identifying Asset Loss:**\nIdentify it precisely as **Capital Loss**. Why? Because Depreciation firmly accounts for regular, expected wear-and-tear during perfectly normal production. A catastrophic flood or earthquake destroying a factory is a tragically completely **unforeseen circumstance**, legally categorized strictly as a Capital Loss.'
  },

  // 2025-26
  {
    id: 'u1-q5-sqp-2026',
    year: '2025-26',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '5',
    question: 'Refer to the given diagram carefully:\nThe arrows C and D represent ______ Market.\n(Choose the correct option to fill up the blank)\nFor Visually Impaired Candidates:\nIn a simplified economy, the flow of Factor Services from Households to Firms and Factor Payments from Firms to Households represents _____ Market.',
    imageUrl: '/assets/images/sqp-2026-q5.png',
    optionA: 'Factor',
    optionB: 'Goods',
    optionC: 'Stock',
    optionD: 'Financial',
    answer: 'A',
    aiExplanation: 'Teacher\'s Voice: **Circular Flow Refresher!**\nIn the two-sector model:\n- **Upper Loop (A & B):** Firms produce and sell *Goods and Services* to Households, who spend their money on them. This represents the **Goods/Product Market**.\n- **Lower Loop (C & D):** Households provide *Factor Services* (Land, Labour, Capital, Enterprise) to Firms. In return, Firms give *Factor Payments* (Rent, Wages, Interest, Profit) back to Households. This specifically represents the **Factor Market**.'
  },
  {
    id: 'u1-q2-sqp-2026',
    year: '2025-26',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '2',
    question: '“Real Gross Domestic Product (GDP) is estimated to attain a level of ₹ 173.82 lakh crore in the year 2023-24. The corresponding Nominal GDP is estimated to stand at ₹ 295.36 lakh crore in the same year.”\nOn the basis of the given data, the value of GDP deflator would be _____.',
    optionA: '295.36',
    optionB: '58.85',
    optionC: '169.92',
    optionD: '173.82',
    answer: 'C',
    aiExplanation: 'Teacher\'s Voice: Let\'s use the basic formula:\n**GDP Deflator = (Nominal GDP / Real GDP) × 100**\nPlug in the numbers: (295.36 / 173.82) × 100.\nSince 295 is much larger than 173, the result must be well over 100.\nCalculation: 1.6992 × 100 = 169.92. This indicates a 69.92% increase in the price level since the base year!'
  },
  {
    id: 'u1-q7-sqp-2026',
    year: '2025-26',
    paperType: 'SQP',
    marks: 1,
    type: 'MCQ',
    questionNumber: '7',
    question: 'Read the following statements carefully:\nStatement 1: Final Goods do not undergo any further transformation at the hands of any producer.\nStatement 2: Final goods may get transformed during their consumption by the ultimate purchaser.\nIn light of the given statements, choose the correct option from the following:',
    optionA: 'Statement 1 is true and Statement 2 is false.',
    optionB: 'Statement 1 is false and Statement 2 is true.',
    optionC: 'Both Statements 1 and 2 are true.',
    optionD: 'Both Statements 1 and 2 are false.',
    answer: 'C',
    aiExplanation: 'Teacher\'s Voice: **Let\'s analyze the journey of a good!**\n- **Statement 1:** True! Once an item is classified as a "Final Good", its journey along the production boundary is over. No more producers will transform it.\n- **Statement 2:** True! Think about buying vegetables (Final Good) to cook a meal at home. The ultimate purchaser (you) transforms them during consumption. But since you aren\'t producing for the market, they remain final goods.'
  },
  {
    id: 'u1-q13b-sqp-2026',
    year: '2025-26',
    paperType: 'SQP',
    marks: 4,
    type: 'SA',
    questionNumber: '13 (B)',
    question: 'Ms. Sarika is a retired government employee. Every month, she earns rental income from a property she owns. She has also invested in fixed deposit, which provide her with interest income. Occasionally, she receives cash transfers from her family members abroad.\nClassify, Ms. Sarika’s income as factor income or transfer income, giving valid reasons in support of your answer.',
    markingScheme: 'The income earned by Ms. Sarika in the form of rent and interest can be classified as factor income, as it is the income earned by the factors of production for rendering their services.\nWhereas; Cash transfers received by Ms. Sarika from her family members abroad can be classified as transfer income as it is the income received without rendering any productive service in return.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 4 M!**\n\n**2 Marks for classifying and explaining Rent/Interest:**\nRent and interest must be classified as **Factor Income** (1 mark). Reason: they are earned by the factors of production for rendering their services (1 mark).\n\n**2 Marks for classifying and explaining Cash Transfers:**\nCash transfers from family must be classified as **Transfer Income** (1 mark). Reason: it is received without rendering any productive service in return (1 mark).'
  },
  {
    id: 'u1-q13b-or-sqp-2026',
    year: '2025-26',
    paperType: 'SQP',
    marks: 4,
    type: 'SA',
    questionNumber: '13 (B) OR',
    question: '“Under the Expenditure Method, the value of Gross Domestic Product (GDP) can be estimated by adding the final expenditure incurred by all the sectors of an economy.”\nIn the light of the given statement, explain the expenditure incurred by any two sectors.',
    markingScheme: 'The final expenditure incurred by the sectors of an economy can be:\n• Private Final Consumption Expenditure: It is the expenditure incurred by households and non-profit institutions serving households on final consumption of goods and services.\n• Net Exports: It refers to the excess of value of exports of goods and services over the value of imports of goods and services, during an accounting year.',
    aiExplanation: 'Teacher\'s Voice: **Here is how to lock in your 4 M!**\n\n**2 Marks for explaining the first sector component (e.g., Households):**\n**Private Final Consumption Expenditure (PFCE):** Explain that it is the expenditure incurred by households (and non-profit institutions serving households) on the final consumption of goods and services. This constitutes the largest chunk of aggregated spending.\n\n**2 Marks for explaining a second sector component (e.g., External Sector):**\n**Net Exports:** Explain that it refers to the excess of value of exports over imports during an accounting year, representing foreign sector spending on domestic goods.\n*(Alternatively, you can explain Government Final Consumption Expenditure [GFCE] or Gross Domestic Capital Formation [GDCF]).*'
  }
];
